version: '3.8'

services:
  backend-clinica:
    build:
      context: ./backend-clinica
      dockerfile: Dockerfile
    container_name: clinica-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend-clinica/prisma:/app/prisma
      - ./backend-clinica/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
