version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: clinica-api
    ports:
      - "3000:3000"
    volumes:
      - ../backend/prisma:/app/prisma
      - ../backend/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
